// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425145541_SeedQualifications")]
    partial class SeedQualifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("PersonQualification", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("PersonQualifications");
                });

            modelBuilder.Entity("Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fundamental knowledge of electrical systems in wind turbines.",
                            Name = "Electrical Systems Basics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Safe handling and operation in high-voltage environments.",
                            Name = "High Voltage Safety"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Inspection and repair of hydraulic turbine systems.",
                            Name = "Hydraulic Systems Maintenance"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Repair of mechanical components like gearboxes and shafts.",
                            Name = "Mechanical Assembly & Repair"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Detecting and repairing structural blade damage.",
                            Name = "Blade Inspection & Repair"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Monitoring turbines via SCADA systems.",
                            Name = "SCADA Systems Operation"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Certified safety procedures for high-altitude work.",
                            Name = "Working at Heights Safety"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Fault detection and maintenance of gearboxes.",
                            Name = "Gearbox Diagnostics"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Identifying and resolving electrical failures.",
                            Name = "Electrical Fault Diagnosis"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fundamentals of turbine assembly and installation.",
                            Name = "Wind Turbine Installation Basics"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Monitoring turbine health using sensor data.",
                            Name = "Condition Monitoring Systems"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Understanding vibration and rotor behavior.",
                            Name = "Rotor Dynamics Understanding"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Handling turbine emergencies and shutdowns.",
                            Name = "Emergency Response Procedures"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Maintaining lubrication systems for moving parts.",
                            Name = "Lubrication Systems Maintenance"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Servicing internal nacelle components.",
                            Name = "Nacelle Systems Maintenance"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Installation and repair of electrical wiring systems.",
                            Name = "Electrical Cabling & Wiring"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Maintenance of converters and inverters.",
                            Name = "Power Conversion Systems"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Connecting turbines to power grid infrastructure.",
                            Name = "Grid Connection Systems"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Understanding control logic and turbine automation.",
                            Name = "Turbine Control Systems"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Planning and scheduling turbine maintenance tasks.",
                            Name = "Preventive Maintenance Planning"
                        });
                });

            modelBuilder.Entity("TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("DurationHours")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskQualification", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredAmount")
                        .HasColumnType("integer");

                    b.HasKey("TaskItemId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("TaskQualifications");
                });

            modelBuilder.Entity("TaskTool", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ToolId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredAmount")
                        .HasColumnType("integer");

                    b.HasKey("TaskItemId", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("TaskTools");
                });

            modelBuilder.Entity("Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("PersonQualification", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithMany("Qualifications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("TaskQualification", b =>
                {
                    b.HasOne("Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskItem", "TaskItem")
                        .WithMany("RequiredQualifications")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskTool", b =>
                {
                    b.HasOne("TaskItem", "TaskItem")
                        .WithMany("RequiredTools")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("TaskItem", b =>
                {
                    b.Navigation("RequiredQualifications");

                    b.Navigation("RequiredTools");
                });
#pragma warning restore 612, 618
        }
    }
}
