// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626210936_remQueries")]
    partial class remQueries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Data.Entitites.BoatPerson", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("BoatNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("PlanId", "BoatNumber", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("BoatPersons");
                });

            modelBuilder.Entity("Backend.Data.Entitites.BoatSchedule", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("BoatNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TripNumber")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Arrival")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Departure")
                        .HasColumnType("time without time zone");

                    b.HasKey("PlanId", "BoatNumber", "TripNumber");

                    b.ToTable("BoatSchedules");
                });

            modelBuilder.Entity("Backend.Data.Entitites.BoatTool", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("BoatNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ToolId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredAmount")
                        .HasColumnType("integer");

                    b.HasKey("PlanId", "BoatNumber", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("BoolTools");
                });

            modelBuilder.Entity("Backend.Data.Entitites.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Backend.Data.Entitites.PersonQualification", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("PersonQualifications");
                });

            modelBuilder.Entity("Backend.Data.Entitites.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Backend.Data.Entitites.PlanBoat", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("BoatNumber")
                        .HasColumnType("integer");

                    b.HasKey("PlanId", "BoatNumber");

                    b.ToTable("Boats");
                });

            modelBuilder.Entity("Backend.Data.Entitites.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fundamental knowledge of electrical systems in wind turbines.",
                            Name = "Electrical Systems Basics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Safe handling and operation in high-voltage environments.",
                            Name = "High Voltage Safety"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Inspection and repair of hydraulic turbine systems.",
                            Name = "Hydraulic Systems Maintenance"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Repair of mechanical components like gearboxes and shafts.",
                            Name = "Mechanical Assembly & Repair"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Detecting and repairing structural blade damage.",
                            Name = "Blade Inspection & Repair"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Monitoring turbines via SCADA systems.",
                            Name = "SCADA Systems Operation"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Certified safety procedures for high-altitude work.",
                            Name = "Working at Heights Safety"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Fault detection and maintenance of gearboxes.",
                            Name = "Gearbox Diagnostics"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Identifying and resolving electrical failures.",
                            Name = "Electrical Fault Diagnosis"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fundamentals of turbine assembly and installation.",
                            Name = "Wind Turbine Installation Basics"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Monitoring turbine health using sensor data.",
                            Name = "Condition Monitoring Systems"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Understanding vibration and rotor behavior.",
                            Name = "Rotor Dynamics Understanding"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Handling turbine emergencies and shutdowns.",
                            Name = "Emergency Response Procedures"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Maintaining lubrication systems for moving parts.",
                            Name = "Lubrication Systems Maintenance"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Servicing internal nacelle components.",
                            Name = "Nacelle Systems Maintenance"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Installation and repair of electrical wiring systems.",
                            Name = "Electrical Cabling & Wiring"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Maintenance of converters and inverters.",
                            Name = "Power Conversion Systems"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Connecting turbines to power grid infrastructure.",
                            Name = "Grid Connection Systems"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Understanding control logic and turbine automation.",
                            Name = "Turbine Control Systems"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Planning and scheduling turbine maintenance tasks.",
                            Name = "Preventive Maintenance Planning"
                        });
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("DurationHours")
                        .HasColumnType("real");

                    b.Property<DateOnly>("ExecutionIntervalEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExecutionIntervalStart")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskQualification", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredAmount")
                        .HasColumnType("integer");

                    b.HasKey("TaskItemId", "QualificationId");

                    b.HasIndex("QualificationId");

                    b.ToTable("TaskQualifications");
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskSchedule", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("BoatNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("PlanId", "BoatNumber", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskSchedules");
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskTool", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ToolId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredAmount")
                        .HasColumnType("integer");

                    b.HasKey("TaskItemId", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("TaskTools");
                });

            modelBuilder.Entity("Backend.Data.Entitites.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Backend.Data.Entitites.Turbine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Turbines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 54.61092f,
                            Longitude = 12.63f,
                            Name = "B1"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 54.60553f,
                            Longitude = 12.63f,
                            Name = "B2"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 54.60014f,
                            Longitude = 12.63f,
                            Name = "B3"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 54.59475f,
                            Longitude = 12.63f,
                            Name = "B4"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 54.58936f,
                            Longitude = 12.63f,
                            Name = "B5"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 54.58397f,
                            Longitude = 12.63f,
                            Name = "B6"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 54.61658f,
                            Longitude = 12.64239f,
                            Name = "B7"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 54.61119f,
                            Longitude = 12.64239f,
                            Name = "B8"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 54.60581f,
                            Longitude = 12.64239f,
                            Name = "B9"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 54.60042f,
                            Longitude = 12.64239f,
                            Name = "B10"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 54.59503f,
                            Longitude = 12.64239f,
                            Name = "B11"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 54.62033f,
                            Longitude = 12.65475f,
                            Name = "B12"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 54.61494f,
                            Longitude = 12.65475f,
                            Name = "B13"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 54.60956f,
                            Longitude = 12.65475f,
                            Name = "B14"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 54.60447f,
                            Longitude = 12.65508f,
                            Name = "B15"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 54.62358f,
                            Longitude = 12.66714f,
                            Name = "B16"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 54.61819f,
                            Longitude = 12.66714f,
                            Name = "B17"
                        },
                        new
                        {
                            Id = 18,
                            Latitude = 54.61281f,
                            Longitude = 12.66714f,
                            Name = "B18"
                        },
                        new
                        {
                            Id = 19,
                            Latitude = 54.62714f,
                            Longitude = 12.6795f,
                            Name = "B19"
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 54.62175f,
                            Longitude = 12.6795f,
                            Name = "B20"
                        },
                        new
                        {
                            Id = 21,
                            Latitude = 54.63067f,
                            Longitude = 12.69189f,
                            Name = "B21"
                        });
                });

            modelBuilder.Entity("Backend.Data.Entitites.BoatPerson", b =>
                {
                    b.HasOne("Backend.Data.Entitites.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Entitites.PlanBoat", "Boat")
                        .WithMany("Persons")
                        .HasForeignKey("PlanId", "BoatNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Backend.Data.Entitites.BoatSchedule", b =>
                {
                    b.HasOne("Backend.Data.Entitites.PlanBoat", "Boat")
                        .WithMany("BoatSchedules")
                        .HasForeignKey("PlanId", "BoatNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");
                });

            modelBuilder.Entity("Backend.Data.Entitites.BoatTool", b =>
                {
                    b.HasOne("Backend.Data.Entitites.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Entitites.PlanBoat", "Boat")
                        .WithMany("Tools")
                        .HasForeignKey("PlanId", "BoatNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Backend.Data.Entitites.PersonQualification", b =>
                {
                    b.HasOne("Backend.Data.Entitites.Person", "Person")
                        .WithMany("Qualifications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Entitites.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Backend.Data.Entitites.PlanBoat", b =>
                {
                    b.HasOne("Backend.Data.Entitites.Plan", "Plan")
                        .WithMany("PlanBoats")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskItem", b =>
                {
                    b.HasOne("Backend.Data.Entitites.Turbine", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskQualification", b =>
                {
                    b.HasOne("Backend.Data.Entitites.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Entitites.TaskItem", "TaskItem")
                        .WithMany("RequiredQualifications")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskSchedule", b =>
                {
                    b.HasOne("Backend.Data.Entitites.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Entitites.PlanBoat", "Boat")
                        .WithMany("TaskSchedules")
                        .HasForeignKey("PlanId", "BoatNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskTool", b =>
                {
                    b.HasOne("Backend.Data.Entitites.TaskItem", "TaskItem")
                        .WithMany("RequiredTools")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.Entitites.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Backend.Data.Entitites.Person", b =>
                {
                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("Backend.Data.Entitites.Plan", b =>
                {
                    b.Navigation("PlanBoats");
                });

            modelBuilder.Entity("Backend.Data.Entitites.PlanBoat", b =>
                {
                    b.Navigation("BoatSchedules");

                    b.Navigation("Persons");

                    b.Navigation("TaskSchedules");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("Backend.Data.Entitites.TaskItem", b =>
                {
                    b.Navigation("RequiredQualifications");

                    b.Navigation("RequiredTools");
                });
#pragma warning restore 612, 618
        }
    }
}
